name: npm build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and publish
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build
    - name: Run tests
      run: npm test -- --watchAll=false
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build


